### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by JeromeBu** [JeromeBu/shared-routes#1]
https://github.com/JeromeBu/shared-routes/assets/22095555/cf1cf984-d9bc-4e6d-9a08-98d4d27f2e4e

**Comment by JeromeBu** [comment]
![show-960](https://github.com/JeromeBu/shared-routes/assets/22095555/036d133f-6681-47c5-b41c-cfca43e3aacb)

**Comment by garronej** [comment]
@JeromeBu If you want to create good quality, small gifs use: https://apps.apple.com/us/app/gifski/id1351639930?mt=12

**Comment by garronej** [comment]
You should definitely check out Screen Studio for this kind of video stuff. It's really cool - you can play around with the cursor size and even zoom in and out to highlight what you're showing. 

Plus, it's got this nifty default editing setup straight away, but you can always tweak it if you're not totally sold on the initial result. 

Here's the link: https://www.screen.studio/

Hope this helps!

**Comment by JeromeBu** [comment]
It does thanks ! I will definitely check it out. 
But it seems https://www.screen.studio would be usefull for longer video. In the readme I don't really see it fit

And thanks for the gif tip !

**Comment by garronej** [comment]
No dude! Even for small video like this it make the world of a difference.  


https://github.com/JeromeBu/shared-routes/assets/6702424/7f00ad79-cb33-4208-951d-1dd23d476131

**Comment by JeromeBu** [comment]
you're right, it does look much better !

**Comment by garronej** [comment]
Check it out, as a below 10M gif thanks to Gifsky

![New Recording May 18 2023 1000 PM](https://github.com/JeromeBu/shared-routes/assets/6702424/94bdf900-b61e-4155-992a-25cef144d83f)

**Comment by garronej** [comment]
Don't say you need to re-record your stuff, just letting you know the tools I use for next time

**Comment by JeromeBu** [comment]
well I did, and it is much better

https://github.com/JeromeBu/shared-routes/assets/22095555/0664640e-ce4b-448b-b8d2-4b0761768b84

**Comment by garronej** [comment]
Yeah! It rocks!

**Comment by JeromeBu** [comment]
Logos assets :

<img width="447" alt="shared-route-with-title" src="https://github.com/JeromeBu/shared-routes/assets/22095555/1368d874-f2e3-492d-aae2-ef3c24ff219b">
<img width="447" alt="shared-route-with-horizontal-titel" src="https://github.com/JeromeBu/shared-routes/assets/22095555/ad05f9b9-805a-4305-83c3-af883f5686a1">

**Comment by garronej** [comment]
<img width="545" alt="image" src="https://github.com/JeromeBu/shared-routes/assets/6702424/dc51491b-0dc3-494d-abab-ebe71157f1e4">
